// resources/js/Components/InputLabel.jsx
export default function InputLabel({
    value,
    className = '',
    children,
    ...props
}) {
    return (
        <label
            {...props}
            className={`label text-sm font-medium ` + className}
        >
            <span className="label-text !text-black dark:!text-white">
                {value ? value : children}
            </span>
        </label>
    );
}

// resources/js/Components/InputLabel.vue
<template>
  <label :class="['label text-sm font-medium', $attrs.class]" v-bind="$attrs">
    <span class="label-text !text-black dark:!text-white">
      <slot>{{ value }}</slot>
    </span>
  </label>
</template>

<script setup>
// value: fallback text when no slot content is provided
defineProps({
  value: String
});
</script>

<style scoped>
</style>
